FROM golang:1.23.0 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod tidy

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server-grpc ./cmd/server-grpc

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/server-grpc .

RUN chmod +x server-grpc

EXPOSE 6605

CMD ["./server-grpc"]