version: '3.8'

services:
  server-api:
    build:
      context: .
      dockerfile: Dockerfile.server-api
    container_name: server-api
    image: server-api:latest
    ports:
      - "6604:6604"
    volumes:
      - /var/www/uploads/files:/files        # For files
      - /var/www/uploads/images:/images     # For images
    env_file:
      - .env
    depends_on:
      - server-grpc
    networks:
      - backend

  server-grpc:
    build:
      context: .
      dockerfile: Dockerfile.server-grpc
    container_name: server-grpc
    image: server-grpc:latest
    ports:
      - "6605:6605"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge
