FROM golang:1.23.0 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod tidy

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server-api ./cmd/server-api

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/server-api .

RUN chmod +x server-api

EXPOSE 6604

CMD ["./server-api"]